version: '3.7'

services:
  postgres:
    image: postgres:16.4
    container_name: postgres
    restart: always
    ports:
      - "${POSTGRES_PORT}:5432"
    env_file: ".env"
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_HOST: ${POSTGRES_HOST}
      MIGRATION_URL: ${MIGRATION_URL}
    volumes:
      - psql_volume:/var/lib/postgresql/data
volumes:
  psql_volume:
